### ISSUE TITLE
GroupConcat - Cannot use object of type Doctrine\\Common\\Lexer\\Token as array

### ISSUE THREAD

**Issue by durimjusaj** [oroinc/doctrine-extensions#104]
When using GroupContact string I got and error that says:

Cannot use object of type Doctrine\\Common\\Lexer\\Token as array.

"file": "/var/www/html/vendor/oro/doctrine-extensions/src/Oro/ORM/Query/AST/Functions/String/GroupConcat.php",
"line": 46

Example of query:
GROUP_CONCAT(DISTINCT ii.paymentRevenueGroup ORDER BY ii.paymentRevenueGroup DESC SEPARATOR ',')

Symfony: 7.0
php: 8.3

**Comment by andreybolonin** [comment]
The same error, by using `CAST`

**Comment by andreybolonin** [comment]
https://github.com/oroinc/doctrine-extensions/pull/106

**Comment by x86demon** [comment]
@durimjusaj thank you for pointing this issue.
I've merged the latest PRs that had to fix the mentioned issue. Kudos to @andreybolonin
