### ISSUE TITLE
Support DATE_FORMAT

### ISSUE THREAD

**Issue by tom10271** [oroinc/doctrine-extensions#37]
https://github.com/beberlei/DoctrineExtensions/blob/master/src/Query/Mysql/DateFormat.php

Oro supports more than berberlei does. I need to use `DateFormat` but currently I need to install 2 both packages.

**Comment by x86demon** [comment]
Hi, @tom10271 
As orocrm/doctrine-extensions is a compatibility layer for MySQL and PostgreSQL all bundled functions must provide same results for all supported DBs.
Is it applicable for you if DATE_FORMAT will support ONLY formats that are intersection of formats described at
https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_date-format
https://www.postgresql.org/docs/current/static/functions-formatting.html#FUNCTIONS-FORMATTING-DATETIME-TABLE

**Comment by x86demon** [comment]
Implemented in #38
