### ISSUE TITLE
[Feature Request] SQLite Support

### ISSUE THREAD

**Issue by paprikamm** [oroinc/doctrine-extensions#50]
Hi,

Is there a plan to add SQLite support?

Thank you.

**Comment by ThomasLandauer** [comment]
I was just about to submit a PR with a first step in this direction (function `YEAR()`). However, on another PR (https://github.com/oroinc/doctrine-extensions/pull/66 ) I'm being asked to sign some weird "Contributor License Agreement" (https://oroinc.com/orocrm/contributor-license-agreement ).

If you remove this Agreement, I will continue to work on SQLite support. If you keep it, I will not come up with any PR.

**Comment by chrisaligent** [comment]
@ThomasLandauer CLA's are pretty common practice on GitHub, I've had to sign a few while contributing to open source projects (including Kubernetes Helm Charts and various other projects).
For more information:
https://en.wikipedia.org/wiki/Contributor_License_Agreement
https://www.clahub.com/pages/why_cla

The gist of it is that you're signing the CLA to say:
1. You aren't contributing code that you don't have permission to contribute (it's not stolen work)
2. You won't take back the code later on
3. You allow Oro to include your code in their software releases

**Comment by ThomasLandauer** [comment]
> CLA's are pretty common practice on GitHub

I've never seen this before on any project.

Anyway, I will definitely not waste my time with wading through page-long legalese (sorry) bullshit. IN OTHER WORDS: WHENEVER I SEE AN ENTIRE PARAGRAPH WRITTEN IN UPPERCASE, I'M OUTTA HERE.
