### ISSUE TITLE
Composer require doesn't load Round.php

### ISSUE THREAD

**Issue by glb2154** [oroinc/doctrine-extensions#51]
Hi, 
aftert using packagist :
composer require oro/doctrine-extensions 
i can't find  Round.php in Oro\ORM\Query\AST\Functions\Numeric

I assume it must have been forgotten when updating this project on packagist.

**Comment by x86demon** [comment]
Hi, @glb2154. Thank you for your attention.
Round is only available in master (dev-master) and was accidentally merged to 1.2
We will prepare 1.3 release that will include this function

**Comment by glb2154** [comment]
yep indeed  i used        
 "oro/doctrine-extensions": "dev-master",
  instead and it worked :)
thanks for your reply
