### ISSUE TITLE
Link from readme 404

### ISSUE THREAD

**Issue by gustawdaniel** [oroinc/doctrine-extensions#63]
In README there is link:

https://www.doctrine-project.org/en/latest/cookbook/dql-user-defined-functions.html

When I click, I see:

```
Page not found
The page you are looking for could not be found. Take a look at one of the pages below instead.

Home
Projects
Contribute
Community
Blog
```

**Comment by hacfi** [comment]
@gustawdaniel Thanks for reporting this! The documentation changed and is now available at https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/cookbook/dql-user-defined-functions.html
