### ISSUE TITLE
Thoughts about support of package

### ISSUE THREAD

**Issue by vladyslavstartsev** [oroinc/doctrine-extensions#70]
I see that this repo is not supported, do you mind I'll start moving functions from here to  https://github.com/beberlei/DoctrineExtensions ?

There, they will get more support then here

**Comment by x86demon** [comment]
Hi, @vladyslavstartsev 
Thank you for your request.
The goal of this project is to add the same set of functions that behave similar on all supported platforms.
For now all required functions are present and works as expected.
If you feel a need in some additional DQL function you may prepare a PR or post a new issue with description of a missing functionality. 
All new functions MUST be implemented for all platforms, documented and covered with tests.

**Comment by anyt** [comment]
> this repo is not supported

The package is well supported. There are no open issues, all the tests are passing in PHP 7.0+, and the package is used in many live projects, including [some popular open-source](https://packagist.org/packages/oro/doctrine-extensions/dependents?order_by=downloads). 

It is simple enough to work for last year, with no need to update anything.
According to the packagist, it's downloaded more than 4M times, and the number is growing every day.

**Comment by ThomasLandauer** [comment]
> The package is well supported.

https://github.com/oroinc/doctrine-extensions/issues/71 shows how "well" supported it is.

**Comment by anyt** [comment]
Thank you for your interest, @ThomasLandauer. It's always much easier to be rude than contributing to the open-source. There are only three open issues in this project. And the fix for the bug you've mentioned will be done in the scope of https://github.com/oroinc/doctrine-extensions/pull/72 that is done in less than two weeks since the issue was raised.

**Comment by ThomasLandauer** [comment]
The issue was raised some 5 months ago: https://github.com/oroinc/doctrine-extensions/pull/69. Which means that it was there when you were claiming in this thread:

> There are no open issues

**Comment by anyt** [comment]
@ThomasLandauer, you are right, but the fix proposed five months ago was not applied to the package for the reasons described in the issue, and no one fixed them, including you, so it was not merged. If you want to contribute to the package - feel free. It is welcome.

It's always up to you to use the package as is, contribute to improve it, or write your own and support it "better" than this one is.
