### ISSUE TITLE
Error when using DATE_FORMAT

### ISSUE THREAD

**Issue by agennari** [oroinc/doctrine-extensions#78]
Hello,

I'm trying to format a date like that:

`->addSelect("DATE_FORMAT(date, '%d %m %Y') as date")`

But I'm getting this error :
![image](https://user-images.githubusercontent.com/65252347/131656561-694e4456-7285-4225-b376-4667342c2723.png)

When I dump

![image](https://user-images.githubusercontent.com/65252347/131656657-266dede1-6bde-4868-8060-9c57082622f1.png)

I got this:
![image](https://user-images.githubusercontent.com/65252347/131656777-b9590542-ef65-4d59-a00c-021422bde189.png)

Configuration:

PHP 8.0.9
Symfony 5.3
Doctrine 2.9
Doctrine extensions 2.0

Is it normal?

Thanks

**Comment by x86demon** [comment]
Hi, @agennari 
Thank you for reporting the issue. We will check it.

**Comment by x86demon** [comment]
Fixed

**Comment by agennari** [comment]
Thanks !
