### ISSUE TITLE
Update to PHP 8

### ISSUE THREAD

**Issue by greeflas** [oroinc/doctrine-extensions#89]
Hi 👋
Thank you for this library!

Do you plan to update to PHP 8?

**Comment by x86demon** [comment]
Hi, @greeflas 
It should be compatible with PHP 8. 
The latest Oro products depend on PHP 8 and this library.

**Comment by greeflas** [comment]
@x86demon ok, thank you.
I asked because I don't see pipeline for PHP 8 in CI. Maybe need to add it.

**Comment by cbeyer** [comment]
Running phpunit I got such messages
`  1x: Method "Doctrine\ORM\Query\AST\Functions\FunctionNode::getSql()" might add "string" as a native return type declaration in the future. Do the same in child class "Oro\ORM\Query\AST\Functions\AbstractPlatformAwareFunctionNode" now to avoid errors or add an explicit @return annotation to suppress this message.
`

**Comment by cbeyer** [comment]
Any news ?

**Comment by x86demon** [comment]
updated dependencies for 2.x and master
