### ISSUE TITLE
Doctrine deprecations

### ISSUE THREAD

**Issue by conradfr** [oroinc/doctrine-extensions#92]
User Deprecated: PostgreSQLPlatform::getName() is deprecated. Identify platforms by their class. (PostgreSQLPlatform.php:1146 called by AbstractPlatformAwareFunctionNode.php:22, https://github.com/doctrine/dbal/issues/4749, package doctrine/dbal)

User Deprecated: Accessing Doctrine\Common\Lexer\Token properties via ArrayAccess is deprecated, use the value, type or position property instead (Token.php:104 called by DocParser.php:691, https://github.com/doctrine/lexer/pull/79, package doctrine/lexer)

This is just warnings, I didn't find at which version they plan to remove those.

**Comment by cbeyer** [comment]
Any news ?

**Comment by x86demon** [comment]
Updated/limited dependencies for 2.x and master.
